### ISSUE TITLE
ssh keygen command doesn't generate expected filetype

### ISSUE THREAD

**Issue by thelifeandtimes** [Native-Planet/anchor#1]
When running the `ssh-keygen -t ed25519 -m PEM` command from the readme, a standard keypair `id_ed25519`/`id_ed25519` is generated. There is not a file with a `.pem` type.

Unclear whether this will have an impact on setup or if the point is just that there needs to be a keypair dedicated to `settings.sh` for anchor to have access to the VPS.

**Comment by yapishu** [comment]
No impact, the script just needs a defined key format so that it can procedurally create the corresponding pubkey. That was what I was working with when I was putting it together but it looks like the command in the script works on normal ed25519 keys as well, I'll update the verbiage.
