### ISSUE TITLE
macOS lacking md5sum dependency?

### ISSUE THREAD

**Issue by thelifeandtimes** [Native-Planet/anchor#2]
After updating the settings script and trying to run, my prompt flags `md5sum` as a command not found.

```
tlat@sourcecode anchor % vim settings.sh
tlat@sourcecode anchor % ./install.sh
./install.sh: line 6: md5sum: command not found
```
It prompted me for a password so i smashed enter a few times and ultimated ran `ctrl + d` to interrupt
```
Password:
Sorry, try again.
Password:
Sorry, try again.
Password:
sudo: no password was provided
sudo: 2 incorrect password attempts
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
./install.sh: line 42: ansible-playbook: command not found
```
I reviewed the install script to see what might be going on, realized why it was looking for my password and then ran it again and it yelled at me about not having a java runtime.
```
tlat@sourcecode anchor % vim install.sh
tlat@sourcecode anchor % ./install.sh  
./install.sh: line 6: md5sum: command not found
Password:
The operation couldn’t be completed. Unable to locate a Java Runtime.
Please visit http://www.java.com for information on installing Java.

# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
# anchor.meaningwave.network:22 SSH-2.0-OpenSSH_8.9p1 Ubuntu-3
./install.sh: line 42: ansible-playbook: command not found
```
Local machine is an M2 macbook air running macOS Monterey, version 12.5 (21G72). Bone stock oem terminal.

**Comment by thelifeandtimes** [comment]
looks like macOS uses `md5` with a slightly different output structure. 
https://www.quora.com/What-is-the-difference-between-OS-X-MD5-and-GNU-MD5sum
https://stackoverflow.com/questions/8996820/how-to-create-md5-hash-in-bash-in-mac-os-x
Will ssh into a different linux box so i don't have to get out of bed...

**Comment by yapishu** [comment]
switched to `openssl rand -hex 20` which should work out of the box on both
